version: "3.7"

services:
  web:
    image: httpd:latest
    ports:
      - "8080:80"
    volumes:
      - ./html/:/usr/local/apache2/htdocs/

    networks:
      - minha-rede

networks:
  minha-rede:
    driver: bridge
